### ISSUE TITLE
Yield Data Missing

### ISSUE THREAD

**Issue by Armadilloa16** [philippbayer/R_gene_analysis#1]
Hi Philipp, 

I was working through reproducing your `./analysis/yield_link.Rmd` and ran into a problem on line 109, seems the data file `./data/yield.txt` is missing? Is this generated by other code and then removed during compiling or something like that, or is this just an oversight? Lovely structure workflowr has... I'm definitely using this for something (not sure exactly what) in the future. 

Cheers, 
Lyron

**Comment by Armadilloa16** [comment]
ping @philippbayer

**Comment by philippbayer** [comment]
Well pinged, sorry about the delay - I ran `git add` but forgot `git push` :P It's there now
